// <auto-generated />
namespace DM.Migrations.User
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Birth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Birth));
        
        string IMigrationMetadata.Id
        {
            get { return "201905240939190_Birth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
